//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long CompanyRegId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdd { get; set; }
        public string CompanyType { get; set; }
    }
}
